### PR TITLE
Update librest to 0.9

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Please see https://github.com/flathub/org.gnome.Photos/pull/38#issuecomment-1257090546

**Comment by hfiguiere** [comment]
anything else than wasn't #38 ?

**Comment by A6GibKm** [comment]
I think it just bumps librest.  iirc I just synced the manifest with upstream.

**Comment by hfiguiere** [comment]
if you want to rebase it, feel free.

**Pull request merged**
