### PR TITLE
Update to gnome-photos 3.34.2 and dependencies

### PR DESCRIPTION
**Pull request by corecontingency**
Lots of bug fixes in here. Built and tested on my computer and it works fine. Ready to merge!

### CODE REVIEW

**Comment by corecontingency** [comment]
Rebased to update to gnome-photos 3.34.2

**Comment by corecontingency** [comment]
Closes issue #13 .

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
