### PR TITLE
Update runtime to gnome 43

### PR DESCRIPTION
**Pull request by hfiguiere**
- Update gegl and babl (ftbs)
- Update tracker miners to 3.4.0

Includes #37

### CODE REVIEW

**Comment by hfiguiere** [comment]
I haven't run it yet

**Comment by hfiguiere** [comment]
With the runtime GNOME 43 I don't see any picture displayed. I still run GNOME 42 on the host.

**Comment by hfiguiere** [comment]
marking as draft until someone that understand better can debug it. Or tell if it is normal.

**Comment by A6GibKm** [comment]
I have 43 on host and it works here at least.

**Comment by hfiguiere** [comment]
> I have 43 on host and it works here at least.

I don't nor do a lot of other users. So there is definitely a problem.

**Comment by A6GibKm** [comment]
I mean we have to understand if being on <43 is actually the issue first

**Comment by hfiguiere** [comment]
Hence my comment:

> marking as draft until someone that understand better can debug it. Or tell if it is normal.

**Comment by A6GibKm** [comment]
Could you please test my PR again? Here it works normally on GNOME 42 in the host.

**Comment by ghost** [comment]
I built `gnome43` branch on Fedora 36 (GNOME 42), ran it and my images from ~/Pictures appear in the UI with no warnings.

Can someone share a log of the "no photos" case? Try running with debug flags enabled like this:

```
flatpak run --env=G_MESSAGES_DEBUG=gnome-photos --env=GNOME_PHOTOS_DEBUG=Tracker app/org.gnome.Photos/x86_64/master
```

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
seems to be working here

**Pull request merged**
