### PR TITLE
Update to 3.32.0

### PR DESCRIPTION
**Pull request by uajain**

### CODE REVIEW

**Comment by uajain** [comment]
I think the build is failing due to `--disable-documentation` config option.
See https://gitlab.gnome.org/GNOME/gnome-photos/commit/993018a3c7e3168f8657aecef8060937c1da96dc

**Comment by uajain** [comment]
From the sharp eyes of Philip Withnall:
Cause of build failures:
> @uajain I think the gnome-photos flathub build failure is because of the `git submodule` commands in the `autogen.sh` script in the 3.32 tarball

> You should wrap the calls to `git` in `autogen.sh` with a check for whether the submodules already exist, like OSTree does: https://github.com/ostreedev/ostree/blob/c9725d0befe0d79931c26483f61acf6b848f452c/autogen.sh#L31
in the case of gnome-photos, I guess you’d check for `subprojects/libgd/README`
The tarball already contains the submodule checkout, so calling `git submodule` is unnecessary when building from a tarball

From IRC:
```
<uajain> I will switch it to meson from now. OK?
<rishi> uajain: Oh, indeed, Flathub is still Autotools. Yes, we should switch.
<rishi> The nightlies have been Meson for a while.
<rishi> Thanks for noticing this!
-*- rishi -> AFK
```

**Comment by uajain** [comment]
CC @debarshiray for code review.

**Comment by monreal** [comment]
Noticed this app is still not updated to 3.32 and I cannot install the test build from above (anymore?)

**Comment by nedrichards** [comment]
bot, build

**Comment by monreal** [comment]
> Build [2952 successful](https://flathub.org/builds/#/builders/32/builds/2952)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/2824/org.gnome.Photos.flatpakref
> ```

This seems to work fine now but still shows the old icon in gnome-shell?

**Comment by debarshiray** [comment]
Thanks, @uajain 

Merged after adding the release notes to the AppData file.

**Pull request merged**
